### ISSUE TITLE
Unread DM Badge Not Functioning Properly

### ISSUE THREAD

**Issue by wilecoyote** [programmer2514/BetterDiscord-CollapsibleUI#109]
Since I've updated to v8 of Collapsible UI I get this annoying counter in the title bar:

![image](https://github.com/programmer2514/BetterDiscord-CollapsibleUI/assets/1034673/ceabcf0d-d28d-442c-b85d-cca52fcae6fa)

When I disable the plugin this counter is gone.

**Comment by programmer2514** [comment]
This is an intended feature - it can be disabled in the plugin settings under the Main category. I did notice it doesn't seem to work correctly with your theme, could you give me the name of the theme so I can improve the feature for others who may need/want it?

**Comment by wilecoyote** [comment]
It's this one:

![image](https://github.com/programmer2514/BetterDiscord-CollapsibleUI/assets/1034673/df34aab4-ddcb-40ea-b411-de1dde0cec01)

**Comment by Zacam** [comment]
Additional Theme Compatibility problem:
ClearVision v6.3.0 (stock or custom)
[https://github.com/ClearVision/ClearVision-v6](url)

Additionally, when using "Remove Old Titlebar" it nests the number over the Blurple icon, because there is no longer a title bar per-se to attach to, so if you are using a smaller server sidebar (to be icons only) it will overlay and look like a double notification badge.

It is also wildly inaccurate and variable to whatever I'm selected to, I know I don't have 114 unreads (dm's or mentions or otherwise), but it'll occasionally go down to 4 if I'm viewing the Shop page.

For others reading, the option in the CollapsibleUI Settings is: Main -> "Persistent Unread DM Badge" (towards the bottom)

**Comment by programmer2514** [comment]
Thank you for the additional information - As of right now, I will continue to improve the feature, but in the next update it will be disabled by default

**Comment by programmer2514** [comment]
Is this issue still happening for anyone?
I still can't seem to reproduce it not functioning as intended.
