### ISSUE TITLE
Members list is getting stuck in forum channels

### ISSUE THREAD

**Issue by Aluerie** [programmer2514/BetterDiscord-CollapsibleUI#124]
## 🪜 Steps to reproduce

1. Open a forum channel;
![image](https://github.com/programmer2514/BetterDiscord-CollapsibleUI/assets/33165440/82bcd984-a666-43dc-aa37-c2572b6db1ce)
2. Click the Members List button;
3. The button will move behind plugin ones (btw the wrong order of buttons should probably be reported as a separate issue, i have these 3 buttons as default values: 1, 2 and 7 and yet members list isn't overwritten by the plugin yet in the screenshot?)
4. But the button is not functional - the list is stuck. It won't ever collapse in currently opened forum channel or any other forum channels including other servers.
![image](https://github.com/programmer2514/BetterDiscord-CollapsibleUI/assets/33165440/8e7d0cc5-94c5-4235-8d75-8b4dcb24a2da)

## 📝Notes
* Collapsing members in non-forum channels continues to work fine and doesn't solve the problem mentioned above. 
* Tested with custom css off and only CollapsibleUI on. 
* The only observed solution is to turn the extension off and click native discord members button.
* Even if we start steps to reproduce with clicking the button in non-forum channels - the list will get stuck in forum channels.

## 🤔

Idk if it's appropriate to ask but I feel like majority of bugs I've seen - happen with members list ; is there any nice way to provide a setting to not hijack the members list/button at all. Eh, at the same time, it's just small bugs randomly appearing 😄

**Comment by programmer2514** [comment]
Thank you for the detailed report! ❤️ 

As for the settings request, no worries at all about asking, user requests are what made this plugin as extensive as it is today. I do not however think it would make much sense to make that a setting at this time, as the plugin itself can be toggled fairly easily if needed. The plugin when enabled does a lot of CSS modifications that would be completely broken if the vanilla Discord members list button were enabled.

And as for the bugs in general, yeah, I know it breaks fairly consistently. That's just the cat and mouse game of the type of modifications this plugin does - since it makes fairly major changes to the UI internally, any small change made on Discord's part is likely to break something in CollapsibleUI. And as much as I wish otherwise, between work and school, I'm not able to fix it as quickly as I would like. I do apologize, I know it's not the most ideal, but I'm grateful to everyone who reports bugs and puts up with my sometimes severely delayed fixes. Y'all are awesome :)

**Comment by Aluerie** [comment]
small issue:
* start discord app (as in fully, i.e. restart the app)
* also, looks like, issue only happens if discord is opened in half-width-screen mode (like when forum channels can't fit both thread list and members list like second screenshot in my issue-message above)
* if member list happens to be uncollapsed 
* and if the first thing you do is open a forum channel 
* then the members button (and actually all other plugin buttons) won't work, the list is stuck too.

"the first thing" part is vital because messing around in other channels beforehand skips the problem.
