### ISSUE TITLE
Ability to maximize in portrait mode on GNU/Linux

### ISSUE THREAD

**Issue by mben42** [programmer2514/BetterDiscord-CollapsibleUI#133]
**Is your feature request related to a problem? Please describe.**
Discord won't maximize on portrait mode on GNU/Linux.

**Describe the solution you'd like**
Add fonctionnality to maximize window in portrait mode.

**Describe alternatives you've considered**
No alternatives found, however Discord can maximize in portrait mode on Windows, it should be possible to make it maximize on GNU/Linux as well.

**Additional context**

**Comment by programmer2514** [comment]
Unfortunately, I cannot feasibly implement this feature because Discord on Linux does not (cannot?) use a custom title bar. Furthermore, it appears that Electron (Discord's backend renderer) does not support controlling the maximize event on Linux. Essentially, though I would love to make this work, it is a Discord/Electron issue and is outside the scope of this project.

**Comment by mben42** [comment]
Sad, thanks for your reply anyway.
