### ISSUE TITLE
Plugin broke again

### ISSUE THREAD

**Issue by Doomelf** [programmer2514/BetterDiscord-CollapsibleUI#136]
Stable 309513 (4058dd9)
Host 1.0.9153 x64 (49397)

**Comment by DontBotherYT** [comment]
Keyboard  shortcuts will not toggle the requested elements. 
Hovering over emoji area does not toggle the folding animation. 

Suggestion: Add a feature so that when the plugin breaks, only certain elements remain toggled, if possible. 

Example: I personally toggle the members list of servers off so I only have the channel list open for easy navigation. If a certain bug causes the collapsing animation to break somehow, have a default "custom" config that only keeps the channel list open, but not the member list. If this is already a possible feature, I'd recommend letting users know about it in the settings menu for Collapsible UI. 

stable 309513 (4058dd9)
Host 0.0.59 x64 
Build Override: N/A 
Linux 64-bit (6.5.0-41-generic)

**Comment by programmer2514** [comment]
Thanks for the report, I should have a fix out in the next 24-48 hours :)

**Comment by programmer2514** [comment]
@DontBotherYT Unfortunately, this is impossible, as my plugin handles all of its element collapsing via listeners and observers. If the plugin fails to load, it cannot keep the necessary elements responsive to user input, and so it generally reverts to Discord's default layout.

At times, depending on what breaks, certain elements of Discord may become non-functional while CollapsibleUI is loaded. I cannot account for this as I do not know what will break next, so in this case I recommend either disabling the plugin, or if you cannot, removing the CollapsibleUI.plugin.js file from your plugins folder and reloading Discord.

I do apologize for inconvenience.

**Comment by DontBotherYT** [comment]
@programmer2514 Completely understandable. Again, it was only a suggestion. Thank you for all the work that you do!
