### ISSUE TITLE
Plugin broke again

### ISSUE THREAD

**Issue by ashergz** [programmer2514/BetterDiscord-CollapsibleUI#137]
What the title says. Less than a month after it was last fixed, the plugin is again not working. No errors and settings page opens up fine as well, but since this morning, the plugin just doesn't do what it should.

Please look into this once more. Thanks.

**Comment by programmer2514** [comment]
Thank you for the report - it may be a bit before I can fix it since I am currently on vacation, but I'll see what I can do. If it's a quick fix I may be able to get it out today.

I do apologize that it keeps breaking - there is nothing I can do except fix it when it does. For some context, every time Discord releases an automatic update, it changes the internal classes of various parts of the UI. Usually this is all the problem is. Unfortunately, unlike most plugins which add a button here or a feature there, CollapsibleUI relies so extensively on modifying Discord's UI that a class change on one of its internal elements is usually enough to make the plugin crash.

**Comment by ashergz** [comment]
Of course man, I totally understand. Just the fact that you're responsive about bug reports is awesome. Enjoy the vacation!

**Comment by ashergz** [comment]
Uh, you sure you don't want to leave this open? Maybe not at high priority, but up so you remember to address it eventually?

**Comment by programmer2514** [comment]
I just fixed it lol

**Comment by ashergz** [comment]
Oh wow you did. Damn that was quick. Thanks!
