### ISSUE TITLE
Changelog keeps opening whenever discord is opened/restarted

### ISSUE THREAD

**Issue by breadbyte** [programmer2514/BetterDiscord-CollapsibleUI#26]

**Comment by programmer2514** [comment]
I cannot seem to reproduce this, but it would be an issue with [ZeresPluginLibrary](https://github.com/rauenzi/BDPluginLibrary/issues), not my plugin.

**Comment by programmer2514** [comment]
After further review, I believe this was caused by the issue fixed in commit 63fed3bf36f18efc108742270bd062b71320ead2. As I don't think I can do anything at all to resolve this issue from my end, I will keep it closed for the time being, but deleting and redownloading the plugin should solve it. If it doesn't, then I believe you have the same issue as #25, which I am actively working to resolve. I apologize for the confusion
