### ISSUE TITLE
Collapsable sections are not showing anymore

### ISSUE THREAD

**Issue by OOlivetti** [programmer2514/BetterDiscord-CollapsibleUI#32]
Hi ! Thank you for the great plugin !
Since last night, I don't know if there was an update or something but the collapsable sections are not showing anymore.
The button of the toolbar are unresponsive as well.
I tried disabling all other plugins and themes but the bugs is still there.

**Comment by programmer2514** [comment]
Hey, so I've been getting a few of these reports, and it always seems to randomly start working on its own? Weird. I've tried reproducing it with no luck. Sometimes it seems like deleting the config file or redownloading the plugin from the GitHub fixes the issue, other times it just takes a reload. For you it seems the issue is persisting?
If it's still happening, do you think you could open Developer Tools (BetterDiscord > Settings > Developer Settings > DevTools, then press Ctrl+Shift+I), go to the Console tab, check if there's any CollapsibleUI error messages, and if so report them back here?

**Comment by OOlivetti** [comment]
Hey, thank you for the quick reply :) 
Here is the error provided by the dev tools
`ca48443fd81954078cd5.js:130 [CollapsibleUI] (v5.1.6) has started.
ca48443fd81954078cd5.js:130 [CollapsibleUI] Reloading...
ca48443fd81954078cd5.js:130 [CollapsibleUI] Failed to restore Members List button. Are you sure it exists?
(anonymous) @ ca48443fd81954078cd5.js:130
CollapsibleUI.plugin.js:765 Uncaught (in promise) TypeError: Cannot read property 'style' of null
    at CollapsibleUI.initialize (CollapsibleUI.plugin.js:765)
    at CollapsibleUI.start (CollapsibleUI.plugin.js:1542)
ca48443fd81954078cd5.js:130 [CollapsibleUI] Failed to restore Members List button. Are you sure it exists?
(anonymous) @ ca48443fd81954078cd5.js:130
ca48443fd81954078cd5.js:130 [CollapsibleUI] (v5.1.6) has stopped.
ca48443fd81954078cd5.js:130 [CollapsibleUI] (v5.1.6) has started.
ca48443fd81954078cd5.js:130 [CollapsibleUI] Reloading...
CollapsibleUI.plugin.js:765 Uncaught (in promise) TypeError: Cannot read property 'style' of null
    at CollapsibleUI.initialize (CollapsibleUI.plugin.js:765)
    at CollapsibleUI.start (CollapsibleUI.plugin.js:1542)
`

**Comment by OOlivetti** [comment]
![image](https://user-images.githubusercontent.com/42735996/169334065-d20a0179-dc2f-4d6f-967a-33f566f85663.png)

**Comment by programmer2514** [comment]
Thank you so much! I can see what the issue is and was finally able to reproduce it. I will have a fix for it released shortly :)
