### ISSUE TITLE
Plugin seems to do nothing

### ISSUE THREAD

**Issue by VirtueAvatar** [programmer2514/BetterDiscord-CollapsibleUI#34]
I downloaded and installed the plugin, discord acknowledged that it was loaded, no new buttons appeared up the top and no parts of discord are collapsible/resizeable. I restarted the discord client just in case, no change. I turned my theme on and off just in case that was interfering, no change. 

I'm using discord stable 132320 and betterdiscord 1.5.3 on windows 10 64-bit.

**Comment by cheatfreak47** [comment]
Well, this sure sounds like my problem. 

Yeah, I have no controls or anything. This appears when I click the settings button in the console.
![image](https://i.imgur.com/BmOrAzp.png)

Here is what appears in the console when I disable the plugin.
![image2](https://i.imgur.com/ZqK3zU4.png)

**Comment by cheatfreak47** [comment]
also, the only data inside of the config:
```{
    "currentVersionInfo": {
        "version": "5.2.9",
        "hasShownChangelog": true
    }
}

**Comment by programmer2514** [comment]
Okay, try out the new release (v5.3.0), I think I've accounted for all the errors reported here (broken startup/settings, empty config file).

**Comment by cheatfreak47** [comment]
Just gave it a try and still no dice, getting this error when I click on the settings button and still no collapsing menus anywhere.
![Discord_2022-06-18_00-32-59](https://user-images.githubusercontent.com/7818664/174422842-6ba55cbb-c725-4d01-a207-605cf2937f83.png)

**Comment by programmer2514** [comment]
@cheatfreak47 Huh, is that the only error being thrown? Because that shouldn't ever happen unless the `start()` function never gets called (meaning the plugin failed to start altogether, which would cause a separate error to be thrown).

I've tested my plugin on a clean installation of BetterDiscord on stable, ptb, and canary and they all check out for me. Try:
1) Deleting `0PluginLibrary.plugin.js` from your plugins folder, reloading Discord, clicking `Download Now` (only once), and reloading again
2) Deleting and [redownloading](https://github.com/programmer2514/BetterDiscord-CollapsibleUI/releases/download/v5.3.0/CollapsibleUI.plugin.js) `CollapsibleUI.plugin.js`
3) Disabling all your plugins and themes except CollapsibleUI and reloading Discord
4) Repairing your BetterDiscord installation

If none of the above solutions fixes the problem and there is still no clear error being thrown (apart from the settings panel one), feel free to contact me on Discord ([@TenorTheHusky#5076](https://discord.com/users/563652755814875146/)) and I can attempt to help you fix the problem there.

Apologies for the inconvenience, and hopefully I can get this issue resolved quickly.

**Comment by cheatfreak47** [comment]
Will try all this later tonight when I have free time. 👍

**Comment by cheatfreak47** [comment]
Good news! For some reason, doing step 1 and 2 there seems to have resolved it!

**Comment by programmer2514** [comment]
Heyy awesome!
I'm not really sure why that was happening (perhaps a problem with Zeres Plugin Library was causing corruption in CollapsibleUI's updater), but I'm glad that fixed it :)

I'm going to mark this issue as resolved, but feel free to let me know if it starts happening again.
