### ISSUE TITLE
suggestion: add conditional autocollapse options

### ISSUE THREAD

**Issue by CoenBeemer** [programmer2514/BetterDiscord-CollapsibleUI#59]
Is it possible to add extra conditions to the autocollapse option besides resolution?
I've found in certain situations(when watching someone's stream) I would like my channels collapsed while in other situations(when going through text channels) I would rather have them open. Toggleing this with the hotkeys is pretty tedious and the autocollapse option seems to be perfect for this.

**Comment by programmer2514** [comment]
I'll admit that this would be a useful feature, but to implement it in a way that would be usable for enough users would require me to abstract a *ton* of properties of the Discord UI, which would be tedious and likely to break. Due to this, if I implement this feature, it won't be in a way that will just work at the click of a button in the settings panel.

I could implement custom conditionals for autocollapsing but the user would have to have a knowledge of programming and Discord's DOM structure to effectively use it, so at best it would be a feature for advanced users only. For instance, if you wanted it to collapse the channels list while in a call, you would put `document.querySelector('.wrapper-1gVUIN')` in the channels list conditional input.

If you think what I suggested is a feature you would use, feel free to respond to this message and I'll look into implementing it.

**Comment by CoenBeemer** [comment]
I wouldn't mind looking into the backend stuff to get this to work, it would be a huge QoL feature to me as the streams would be very small otherwise on my vertical monitor. Would be worth the effort to me.

**Comment by programmer2514** [comment]
Added in db0434d.
For your specific use case, if you only want it to collapse while in a call, put `document.querySelector('.wrapper-1gVUIN')` in the channel list box like this:
![Untitled](https://user-images.githubusercontent.com/43104632/205985896-70b6fc77-5d77-4c6b-93e9-d740449ba920.png)
