### ISSUE TITLE
The collapsing toggle buttons are not appearing in a specific case

### ISSUE THREAD

**Issue by cheatfreak47** [programmer2514/BetterDiscord-CollapsibleUI#76]
Hi, I've noticed that sometimes, when the window is small enough, the usual top button doesn't appear in DMs, specifically while you have the "User Profiles (Unavailable)" button.

Frankly I feel like this window size check aught to just be patched out entirely when using Collapsible UI, which would probably prevent this problem from happening in the first place.

![Discord_2023-02-18_11-02-37](https://user-images.githubusercontent.com/7818664/219875889-63542372-22a0-44fa-bcd0-4970c81c5c88.png)

Also, while on this situation, entering and exiting the regular discord settings menu causes the menu to appear again, next to this "User Profiles (Unavailable)" button, with the Window Bar icon instead.

**Comment by programmer2514** [comment]
This unfortunately to the best of my knowledge cannot be fixed. The user profile panel actually has to be present in the DOM in order for my plugin to detect that it exists, and since Discord is still rolling out the feature, it currently isn't stable enough to correctly account for. I know it's an issue that is kind of annoying, but realistically the only thing that will resolve it is waiting for Discord to fully implement the feature.
