### ISSUE TITLE
Feature Request: Collapse Messagebox Icons

### ISSUE THREAD

**Issue by notblam** [programmer2514/BetterDiscord-CollapsibleUI#79]
![image](https://user-images.githubusercontent.com/61704528/222322978-d68b061f-0fb7-4c85-9896-d4f685696bac.png)

Loving this plugin, I prefer using discord in this really small window.  However, it's not very practical to type when these icons take up half the message box.  Can you make this collapsible as well?

**Comment by programmer2514** [comment]
Should be implemented in v7.1.1

Thanks for the suggestion!

**Comment by Jugom** [comment]
So.. I have an issue with this. lol
when it's collapsed, it shows an icon I don't really care about. and the emoji (or GIF) icon which is the one I use the most is hidden. so I prefer it to remain uncollapsed for faster clicking.
Problem is; when I click on the disable message button thingy in the main settings, it locks it in the collapsed position instead of the uncollaped one depriving me from all access to the emoji and GIF buttons. 

so, either a fix it so the disable option leaves it uncollapsed, or allow to select what button(s) to show when locked. 
There's a remove chat buttons plugin I was using for this before, but sadly it also broke with the last update.

cheers

**Comment by programmer2514** [comment]
@Jugom 
> Problem is; when I click on the disable message button thingy in the main settings, it locks it in the collapsed position instead of the uncollaped one depriving me from all access to the emoji and GIF buttons.

This is a bug; I should be able to get that fixed in the next update.

> There's a remove chat buttons plugin I was using for this before, but sadly it also broke with the last update.

You should be able to use this custom CSS to hide the buttons you don't want:
```
/* Hides the gift button */
[aria-label="Send a gift"] {
    display: none;
}

/* Hides the GIF button */
[aria-label="Open GIF picker"] {
    display: none;
}

/* Hides the sticker button */
[aria-label="Open sticker picker"] {
    display: none;
}
```
