### ISSUE TITLE
Bug with collapsable message box

### ISSUE THREAD

**Issue by notblam** [programmer2514/BetterDiscord-CollapsibleUI#80]
https://gyazo.com/e382b061e35a053384abeffcb2e4f914

Wasn't sure if this was intended or not so I figured I would post.  Shouldn't this collapse completely instead of showing parts of an icon?  Also I'm getting kind of a weird jitter if I don't have my cursor completely centered.  

I'm blown away at how quickly you got this this done and released.  Thanks a ton for implementing this.

**Comment by programmer2514** [comment]
Are you using a theme? If so, which one?

The jitter and the extra bit of the icon both seem to be caused by some rearranging of UI elements by a theme.
I can implement a setting to tweak the collapsed width of the message bar buttons, but as for the jittering, I'd probably need to implement some compatibility code.

**Comment by notblam** [comment]
> Are you using a theme? If so, which one?
> 
> The jitter and the extra bit of the icon both seem to be caused by some rearranging of UI elements by a theme. I can implement a setting to tweak the collapsed width of the message bar buttons, but as for the jittering, I'd probably need to implement some compatibility code.

My theme is a modified version of Zelk.  I disable the theme and still get this behavior.  

The jittering isn't too bad, it doesn't seem to be as bad anymore, maybe I'm getting used to it.  But I would love to see the tweak of the collapsed width so that it hides completely.
