### ISSUE TITLE
When hidden, the Member list jumps open after switching channels or servers

### ISSUE THREAD

**Issue by Andrew6rant** [programmer2514/BetterDiscord-CollapsibleUI#9]
Here is a screen recording that shows it better:

https://user-images.githubusercontent.com/57331134/140177294-4688f44a-6d6c-416b-a153-c6666bd1707d.mp4

I've fixed this in my personal fork (by removing the code haha), because I don't care much for the sliding animations, but I thought I'd make an issue report anyways

**Comment by programmer2514** [comment]
Fixed by refactoring animation code in pre-release

**Comment by Andrew6rant** [comment]
This issue seems to have popped up again a few versions ago, the tab still jumps open on version 5.4.3

**Comment by programmer2514** [comment]
If you are referring to the quick flash, unfortunately that is due to either Discord or BetterDiscord redoing some stuff internally that slowed down panel switching. I can't really resolve that as the panel is only visible for the amount of time it takes my plugin to process that it exists (which is handled by a default method, not something I wrote)
