### ISSUE TITLE
Suggestion: Collapse Role groups in member list

### ISSUE THREAD

**Issue by FaceCrap** [programmer2514/BetterDiscord-CollapsibleUI#99]
Something I've been looking for a long time is the option to collapse the role groups in the member list. 
Some servers have so many members that it's undoable to find the online status of someone you know.

**Comment by programmer2514** [comment]
This may or may not actually be possible, but I'll definitely keep it on my radar

**Comment by programmer2514** [comment]
After further review, this is sadly impossible due to how Discord loads the members list. Essentially, Discord only loads the members who are currently in view to decrease polling rates - implementing a role-group collapse would require some way to bypass this, and any attempt to do so would create API spam and cause your account to be rate limited or deleted for violating Discord's ToS.

**Comment by FaceCrap** [comment]
Was afraid of that, had looked at it myself a long time ago before it became too complex for me to even try and write a plugin and didn't see a way back then too. Had hoped someone with a better understanding of the Discord structure susch as yourself, would know alternative ways around it.
Thanks anyways for looking into it.
